<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2.2 (Python 3.13.5 on win32)" generated="2025-07-04T03:08:15.046324" rpa="false" schemaversion="5">
<suite id="s1" name="Qa-Test" source="C:\Users\mehme\Documents\cours\M1GL\qa-test">
<suite id="s1-s1" name="Lab6" source="C:\Users\mehme\Documents\cours\M1GL\qa-test\lab6">
<suite id="s1-s1-s1" name="Testcases" source="C:\Users\mehme\Documents\cours\M1GL\qa-test\lab6\testcases">
<suite id="s1-s1-s1-s1" name="Fakestore Api Tests" source="C:\Users\mehme\Documents\cours\M1GL\qa-test\lab6\testcases\fakestore_api_tests.robot">
<kw name="Create Session To Petstore" owner="fakestore_keywords" type="SETUP">
<kw name="Create Session" owner="RequestsLibrary">
<msg time="2025-07-04T03:08:15.453898" level="INFO">Creating Session using : alias=Petstore, url=https://petstore.swagger.io/v2, headers={'Content-Type': 'application/json'},                     cookies={}, auth=None, timeout=None, proxies=None, verify=False,                     debug=0 </msg>
<arg>Petstore</arg>
<arg>${BASE_URL}</arg>
<arg>headers=${HEADERS}</arg>
<doc>Create Session: create a HTTP session to a server</doc>
<status status="PASS" start="2025-07-04T03:08:15.453569" elapsed="0.000688"/>
</kw>
<kw name="Log To Console" owner="BuiltIn">
<arg>Created session to Petstore at ${BASE_URL}</arg>
<doc>Logs the given message to the console.</doc>
<status status="PASS" start="2025-07-04T03:08:15.454426" elapsed="0.000671"/>
</kw>
<status status="PASS" start="2025-07-04T03:08:15.453072" elapsed="0.002260"/>
</kw>
<test id="s1-s1-s1-s1-t1" name="Verify 404 Error" line="32">
<kw name="Set Variable" owner="BuiltIn">
<msg time="2025-07-04T03:08:15.456562" level="INFO">${pet_id} = 999</msg>
<var>${pet_id}</var>
<arg>999</arg>
<doc>Returns the given values which can then be assigned to a variables.</doc>
<status status="PASS" start="2025-07-04T03:08:15.456284" elapsed="0.000413"/>
</kw>
<kw name="Verify 404 Error" owner="fakestore_keywords">
<kw name="GET On Session" owner="RequestsLibrary">
<msg time="2025-07-04T03:08:16.222817" level="INFO">GET Request : url=https://petstore.swagger.io/v2/pet/999 
 path_url=/v2/pet/999 
 headers={'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Type': 'application/json'} 
 body=None 
 </msg>
<msg time="2025-07-04T03:08:16.223182" level="INFO">GET Response : url=https://petstore.swagger.io/v2/pet/999 
 status=404, reason=Not Found 
 headers={'Date': 'Fri, 04 Jul 2025 03:08:16 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, DELETE, PUT', 'Access-Control-Allow-Headers': 'Content-Type, api_key, Authorization', 'Server': 'Jetty(9.2.9.v20150224)'} 
 body={"code":1,"type":"error","message":"Pet not found"} 
 </msg>
<msg time="2025-07-04T03:08:16.223366" level="INFO">C:\Users\mehme\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'petstore.swagger.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(</msg>
<msg time="2025-07-04T03:08:16.223943" level="FAIL">HTTPError: 404 Client Error: Not Found for url: https://petstore.swagger.io/v2/pet/999</msg>
<var>${response}</var>
<arg>Petstore</arg>
<arg>/pet/${pet_id}</arg>
<doc>Sends a GET request on a previously created HTTP Session.</doc>
<status status="FAIL" start="2025-07-04T03:08:15.457871" elapsed="0.768383">HTTPError: 404 Client Error: Not Found for url: https://petstore.swagger.io/v2/pet/999</status>
</kw>
<kw name="Should Be Equal As Integers" owner="BuiltIn">
<arg>${response.status_code}</arg>
<arg>404</arg>
<doc>Fails if objects are unequal after converting them to integers.</doc>
<status status="NOT RUN" start="2025-07-04T03:08:16.226459" elapsed="0.000128"/>
</kw>
<kw name="Log To Console" owner="BuiltIn">
<arg>Verified 404 error for pet ID ${pet_id}</arg>
<doc>Logs the given message to the console.</doc>
<status status="NOT RUN" start="2025-07-04T03:08:16.226692" elapsed="0.000173"/>
</kw>
<arg>${pet_id}</arg>
<status status="FAIL" start="2025-07-04T03:08:15.457079" elapsed="0.769948">HTTPError: 404 Client Error: Not Found for url: https://petstore.swagger.io/v2/pet/999</status>
</kw>
<kw name="Log To Console" owner="BuiltIn">
<arg>Verified 404 error for pet ID: ${pet_id}</arg>
<doc>Logs the given message to the console.</doc>
<status status="NOT RUN" start="2025-07-04T03:08:16.227602" elapsed="0.000132"/>
</kw>
<doc>VÃ©rifie que l'ID du pet n'existe pas</doc>
<status status="FAIL" start="2025-07-04T03:08:15.455500" elapsed="0.773023">HTTPError: 404 Client Error: Not Found for url: https://petstore.swagger.io/v2/pet/999</status>
</test>
<status status="FAIL" start="2025-07-04T03:08:15.086673" elapsed="1.144227"/>
</suite>
<status status="FAIL" start="2025-07-04T03:08:15.083767" elapsed="1.148911"/>
</suite>
<status status="FAIL" start="2025-07-04T03:08:15.079452" elapsed="1.154126"/>
</suite>
<status status="FAIL" start="2025-07-04T03:08:15.055051" elapsed="1.180000"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat name="Qa-Test" id="s1" pass="0" fail="1" skip="0">Qa-Test</stat>
<stat name="Lab6" id="s1-s1" pass="0" fail="1" skip="0">Qa-Test.Lab6</stat>
<stat name="Testcases" id="s1-s1-s1" pass="0" fail="1" skip="0">Qa-Test.Lab6.Testcases</stat>
<stat name="Fakestore Api Tests" id="s1-s1-s1-s1" pass="0" fail="1" skip="0">Qa-Test.Lab6.Testcases.Fakestore Api Tests</stat>
</suite>
</statistics>
<errors>
<msg time="2025-07-04T03:08:15.038339" level="ERROR">Error in file 'C:\Users\mehme\Documents\cours\M1GL\qa-test\projet-cours-3\resources\auth.robot' on line 20: Creating keyword 'Saisir le bon username' failed: Keyword with same name defined multiple times.</msg>
<msg time="2025-07-04T03:08:15.038948" level="ERROR">Error in file 'C:\Users\mehme\Documents\cours\M1GL\qa-test\projet-cours-3\resources\auth.robot' on line 29: Creating keyword 'Saisir un mauvais mot de passe' failed: Keyword with same name defined multiple times.</msg>
</errors>
</robot>
